spring:
  application:
    name: MidgardCharacterOrganizer
#  profiles:
#    active: default
#  jpa:
#    hibernate:
#      ddl-auto: create-drop
  #    dialect: org.hibernate.dialect.H2Dialect
#    naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

#spring.datasource.url=jdbc:mysql://localhost/test
#spring.datasource.username=dbuser
#spring.datasource.password=dbpass
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver

server:
  port: 8080


---

spring:
  profiles: dev
  datasource:
    platform: hsqldb
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true