package de.domson.midgard.weapon;

/**
 * Created by domson on 30.03.17.
 */
public enum WeaponType {
    EINHANDSCHLAGWAFFEN, EINHANDSCHWERTER, FECHTWAFFEN,
    KETTENWAFFEN, SPIESSWAFFEN, STICHWAFFEN, STOCKWAFFEN,
    ZAUBERSTÄBE, ZWEIHANDSCHLAGWAFFEN, ZWEIHANDSCHWERTER,
    WAFFENLOSER_KAMPF, STIELWURFWAFFEN, WURFKLINGEN,
    WURFSCHEIBEN, WURFSPIESSE, ARMBRÜSTE, BLASROHRE,
    BÖGEN, SCHLEUDERN, SCHILDE, PARIERWAFFEN
}
